# Default values for omar-wms.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicas: 1

appName: omar-wms

global:
  dockerRepository: nexus-docker-private-group.ossim.io
  imagePullSecret:
    registry: null
    username: null
    password: null
  hostname: omar-dev.ossim.io

  createIngress: true
  useTls: false
  useTLSClientAuth: false
  sslCertSecretName: null
  authSslCertSecretName: null

  createImagePullSecret: true
  useImagePullSecret: true

  createHpa: true
  useSpringConfigServer: false

# These variables can be overridden because of the use of the 'pluck' function:
# - createIngress
# - useTls
# - useTlsClientAuth
# - createImagePullSecret
# - createHpa
# - createPVs
# - useSpringConfigServer

resources:
  limits:
    cpu: 1500m
    memory: 1000Mi
  requests:
    cpu: 500m
    memory: 500Mi

minReplicas: 4
maxReplicas: 10
targetCpu: 50

hostnames: []

image:
  name: omar-wms
  tag: dev
  pullPolicy: Always

ingressPath: /omar-wms
internalPort: 8080
externalPort: 8080

livenessProbe:
  failureThreshold: 5
  initialDelaySeconds: 60
  periodSeconds: 15
  successThreshold: 1
  timeoutSeconds: 3

readinessProbe:
  path: /omar-wms/actuator/health
  failureThreshold: 15
  initialDelaySeconds: 30
  periodSeconds: 15
  successThreshold: 1
  timeoutSeconds: 3

terminationGracePeriodSeconds: 30

envVars:
  SPRING_CLOUD_CONFIG_LABEL: master

configmaps: {}

extraVolumes: []

extraVolumeMounts: []

extraInitContainers: []

sideCars: []
