apiVersion: skaffold/v2beta7
kind: Config
metadata:
  name: omar-wms
build:
  artifacts:
    - image: registry.iap.maxar.com/gegd/omar/omar-wms
      jib: 
        project: omar-wms-app
      context: ./apps/omar-wms-app
  tagPolicy:
    sha256: {}
deploy:
  helm:
    releases:
      - name: omar-wms # this is the helm release name                
        chartPath: ./apps/omar-wms-app/chart
        valuesFiles:
          - ./apps/omar-wms-app/values-dev.yaml # provides values to override defaults in chart
        namespace: omar-3pa-dev
        setValueTemplates:
          image.tag: latest
          image.name: omar-wms
