info:
  app:
    name: '@info.app.name@'
    version: '@info.app.version@'
    grailsVersion: '@info.app.grailsVersion@'

dataSource:
  driverClassName: org.postgresql.Driver
  username: ${omarDb.username}
  password: ${omarDb.password}
  pooled: true
  jmxExport: true

environments:
  development:
    dataSource:
      dbCreate: create-drop
      url: jdbc:postgresql://${omarDb.host}:${omarDb.port}/${omarDb.name}
  test:
    dataSource:
      dbCreate: update
      url: jdbc:postgresql://${omarDb.host}:${omarDb.port}/${omarDb.name}
  production:
    dataSource:
      dbCreate: none
      url: jdbc:postgresql://${omarDb.host}:${omarDb.port}/${omarDb.name}
      properties:
        jmxEnabled: true
        initialSize: 5
        maxActive: 50
        minIdle: 5
        maxIdle: 25
        maxWait: 10000
        maxAge: 600000
        timeBetweenEvictionRunsMillis: 5000
        minEvictableIdleTimeMillis: 60000
        validationQuery: SELECT 1
        validationQueryTimeout: 3
        validationInterval: 15000
        testOnBorrow: true
        testWhileIdle: true
        testOnReturn: false
        jdbcInterceptors: ConnectionState
        defaultTransactionIsolation: 2 # TRANSACTION_READ_COMMITTED

grails:
  gorm:
    reactor:
      events: false
  mime:
    disable:
      accept:
        header:
          userAgents:
            - Gecko
            - WebKit
            - Presto
            - Trident
    types:
      all: '*/*'
      atom: application/atom+xml
      css: text/css
      csv: text/csv
      form: application/x-www-form-urlencoded
      html:
        - text/html
        - application/xhtml+xml
      js: text/javascript
      json:
        - application/json
        - text/json
      multipartForm: multipart/form-data
      pdf: application/pdf
      rss: application/rss+xml
      text: text/plain
      hal:
        - application/hal+json
        - application/hal+xml
      xml:
        - text/xml
        - application/xml
  views:
    gsp:
      encoding: UTF-8
      htmlcodec: xml
      codecs:
        expression: html
        scriptlet: html
        taglib: none
        staticparts: none
    default:
      codec: html
hibernate:
  hbm2ddl:
    auto: update
  cache:
    queries: false
    use_second_level_cache: false
    use_query_cache: false

---
grails:
  cors:
    enabled: true
  resources:
    pattern: '/**'
  plugin:
    console:
      enabled: true
      csrfProtection:
        enabled: false

server:
  port: 8080
  servlet:
    context-path: /omar-wms
management:
  endpoints:
    enabled-by-default: true
    web:
      base-path: '/actuator'
      exposure:
        include: '*'
environments:
  production:
    spring:
      h2:
        console:
          enabled: true
          settings:
            web-allow-others: true
---
omarDb:
  host: localhost
  port: 5432
  username: postgres  
  password: postgres

environments:
  development:
    omarDb:
      name: omardb-dev
  production:
    omarDb:
      name: omardb-prod
---
omar:
  wms:
    stager:
      # Is the location of the stager API.  This is used to update the last access date for images.
      url: http://omar-stager-app:8080/omar-stager/dataManager
    geoscript:
      # Is the location of the geoscript API for the query service.  This is used to query the layers in the LAYERS parameter.
      url: http://omar-geoscript-app:8080/omar-geoscript/geoscriptApi

    oms:
      chipper:
        # Is the location of the chipper endpoint for chipping imagery.
        url: http://omar-oms-app:8080/omar-oms/chipper
        # Is the default histogram operation that is applied if no argument is passed in the styles.
        # e.g.: "none", "auto-minmax", "auto-percentile", "std-stretch-1", "std-stretch-2", or "std-stretch-3"
        histOp: auto-minmax
    mosaic:
      limit: 50
# Define the http protocols that swagger will use
swagger:
  schemes:
    - HTTPS
    - HTTP                  