apiVersion: v1
kind: DeploymentConfig
metadata:
  name: omar-wms-app
  namespace: omar-dev
  selfLink: /oapi/v1/namespaces/omar-dev/deploymentconfigs/omar-wms-app
  uid: dc9b6c4c-82c2-11e7-ba3b-0e704fd9c8b2
  resourceVersion: '8863876'
  generation: 659
  creationTimestamp: '2017-08-16T20:38:29Z'
  labels:
    app: omar-openshift
  annotations:
    openshift.io/generated-by: OpenShiftNewApp
spec:
  strategy:
    type: Rolling
    rollingParams:
      updatePeriodSeconds: 1
      intervalSeconds: 1
      timeoutSeconds: 600
      maxUnavailable: 25%
      maxSurge: 25%
    resources: {}
    activeDeadlineSeconds: 21600
  triggers:
    - type: ConfigChange
    - type: ImageChange
      imageChangeParams:
        automatic: true
        containerNames:
          - omar-wms-app
        from:
          kind: ImageStreamTag
          namespace: o2
          name: 'omar-wms-app:latest'
        lastTriggeredImage: >-
          172.30.181.173:5000/o2/omar-wms-app@sha256:e6b93c7180197190e97d7cb0f1805d5d160b2d4dc8a67e70122e58e38135914f
  replicas: 1
  test: false
  selector:
    app: omar-openshift
    deploymentconfig: omar-wms-app
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: omar-openshift
        deploymentconfig: omar-wms-app
      annotations:
        openshift.io/generated-by: OpenShiftNewApp
    spec:
      volumes:
        - name: volume-wms
          persistentVolumeClaim:
            claimName: ossim-data-dev-pvc
      containers:
        - name: omar-wms-app
          image: >-
            172.30.181.173:5000/o2/omar-wms-app@sha256:e6b93c7180197190e97d7cb0f1805d5d160b2d4dc8a67e70122e58e38135914f
          ports:
            - containerPort: 8080
              protocol: TCP
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: dev
            - name: SPRING_CLOUD_CONFIG_LABEL
              value: master
          resources: {}
          volumeMounts:
            - name: volume-wms
              mountPath: /data
          livenessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 60
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          readinessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 30
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          terminationMessagePath: /dev/termination-log
          imagePullPolicy: Always
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
status:
  latestVersion: 653
  observedGeneration: 659
  replicas: 1
  updatedReplicas: 1
  availableReplicas: 1
  unavailableReplicas: 0
  details:
    message: image change
    causes:
      - type: ImageChange
        imageTrigger:
          from:
            kind: ImageStreamTag
            namespace: o2
            name: 'omar-wms-app:latest'
  conditions:
    - type: Available
      status: 'True'
      lastUpdateTime: '2017-10-31T19:47:06Z'
      lastTransitionTime: '2017-10-31T19:47:06Z'
      message: Deployment config has minimum availability.
    - type: Progressing
      status: 'True'
      lastUpdateTime: '2017-11-30T12:34:44Z'
      lastTransitionTime: '2017-11-30T12:34:43Z'
      reason: NewReplicationControllerAvailable
      message: replication controller "omar-wms-app-653" successfully rolled out
  readyReplicas: 1
